# Generated by Django 5.1.7 on 2025-04-13 20:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Comment', '0001_initial'),
        ('Reponsebug', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='commentresponse',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='commentresponse',
            name='response_bug',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='Reponsebug.bugresponse'),
        ),
    ]
