# Generated by Django 5.1.7 on 2025-04-13 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bug', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bugreport',
            name='tags',
            field=models.ManyToManyField(blank=True, to='Bug.tags'),
        ),
    ]
